### ISSUE TITLE
Cannot get all stars at once

### ISSUE THREAD

**Issue by isaachinman** [HacktheUniverse/star-api#44]
Despite [the very first example](https://hacktheuniverse.github.io/star-api/) in the documentation implying that it's possible to fetch the entire database, it's not. I believe this is because of Socrata's [limit of 1000 requests per hour](http://dev.socrata.com/consumers/getting-started.html)(?). There's no point of having a database of 100k items if you can't fetch all of them simultaneously to facilitate client-side live searching, even if just on one variable - say "label". Suggestions?

**Comment by surenm** [comment]
Hey @isaachinman, We wanted to get that here - #29. I am trying to put together a that will let you access everything at once, but can you let me know what is the exact use case? 

Also starapi.herokuapp.com is not hosted out of Socrata's data source. It has its own database, so once we identify what you exactly you want, I can do something about it!

**Comment by isaachinman** [comment]
@surenm Ah! So sorry for opening a duplicate issue then. Would you like me to close this issue and discuss further on #29?

**Comment by surenm** [comment]
Lets continue here - may be your use case is simpler than solving #29

**Comment by isaachinman** [comment]
I take it then that you guys aren't associated with [this API](http://dev.socrata.com/foundry/#/data.nasa.gov/5bv2-dyn2)?

**Comment by surenm** [comment]
@isaachinman That API is based on our work but no, we don't own that. If we make any significant changes to the data, we can ask to take those changes upstream! Does that help?

**Comment by isaachinman** [comment]
@surenm It's less to do with changes to the data and more to do with structural changes in this case, I think. Either way, I think there's a need to be able to fetch the entire database at once.

**Comment by isaachinman** [comment]
@surenm The Socrata API is now listed as private and XML requests to it are failing, any idea why?

**Comment by surenm** [comment]
@isaachinman I dunno why that happened, I am not connected with them. May be write to them? 

Alternatively you can use star-api.herokuapp.com for your API if that helps!

**Comment by isaachinman** [comment]
@surenm Will do. I was in contact with NASA and the American Museum of Natural History, and there appeared to be some kind of confusion about data ownership. Also, you don't appear to have an Access-Control-Allow-Origin header?

**Comment by surenm** [comment]
@isaachinman Yes, that header was missing. Have added now at https://github.com/HacktheUniverse/star-api/commit/2266955db4c1a7780da2eaee99cd7410884b3e4c.

Have also pushed to star-api.herokuapp.com. Can you check and let me know?

What kind of API are you looking for getting all the stars at one go?

**Comment by isaachinman** [comment]
@surenm I'm still getting a Access-Control-Allow-Origin header error when calling:

    http://star-api.herokuapp.com/api/v1/stars

And yup, I'd like to fetch the entirety of the database, as I'm interested in setting up client-side searching.

**Comment by surenm** [comment]
https://www.evernote.com/shard/s16/sh/81fa4be1-bca4-44c6-8bd0-504119eeeab1/732c57eb1023574dbd592a75b3bbaed0 - the request does seem to have cors enabled. Can you please clear cache and try again?

**Comment by isaachinman** [comment]
@surenm Yes, thanks - that seems to be working now. And your API is *much* quicker than the Socrata SODA API. Still though, as you're aware, the following request only returns an array with a length of 500:

    http://star-api.herokuapp.com/api/v1/stars

Also, do you guys issue API keys/tokens for usage stats, etc?

**Comment by surenm** [comment]
Hey @isaachinman, no, we haven't managed to add analytics to the API. Its fast now because may be you are the only one using it ;) 

Yes, I am working on an endpoint that gives the entire stars list. The challenge is there is 100K stars and that can easily be few MB's worth of data. Both the query and the response may have to be cached. So figuring out how to do it the best way!

**Comment by isaachinman** [comment]
@surenm I see what you're saying, although surely if the request is async it shouldn't matter too much? Or, alternatively, what about just fetching all the labels (or any other attribute) - this should bring the size down considerably and would be adequate for client-side searching.

**Comment by sanderblue** [comment]
Hi there. It's been a while since this thread was updated, but I'd to like chime in even if it's a year later. 

I would also like to fetch a full response of all the stars in the database. You could create paginated responses to help make the size of the response smaller. e.g. `http://star-api.herokuapp.com/api/v1/stars?page=1` or `http://star-api.herokuapp.com/api/v1/stars/page/1`, `http://star-api.herokuapp.com/api/v1/stars/page/2`, etc.

**Comment by isaachinman** [comment]
Actually, assuming these guys are still using a Socrata SODA API, it'd just be an offset param, eg:

```
http://star-api.herokuapp.com/api/v1/stars?offset=50&limit=25
```

In this example you'd be on page 3. This allows for flexible page sizes; keep all of that login on your frontend.

**Comment by mienaikoe** [comment]
It's been almost a year, but I'd also like to chime in. I worked with the same data when these guys did and did client-side gpu rendering for the stars. If you want to have all the stars on the client, **you should not be using an API call to do that**. The reason is: 
1) it's slow, 
2) the star data are not likely to change, and 
3) It's unreasonable to tax the API that much. 

If you want the data, you should keep it in a file locally to your app. During the hackathon I parsed the raw files and stored them as json. You are welcome to copy those files:   https://github.com/HacktheUniverse/cosmos/tree/master/data

**Comment by surenm** [comment]
@mienaikoe is correct, its preferable to download the data locally in batches using the api when you need all the stars.
